### ISSUE TITLE
Invalid write to a sparse field doesn't give an error

### ISSUE THREAD

**Issue by BenWeber42** [dawn-ico/dusk#45]
https://github.com/dawn-ico/dusk/blob/ad57bd5a3a2568e83b3bd13aacc9daedbcdf86f4/tests/stencils/test_sparse_fill.py#L104-L112

**Comment by mroethlin** [comment]
will be fixed with (this dawn PR)[https://github.com/MeteoSwiss-APN/dawn/pull/1025]
