### ISSUE TITLE
Default the Offset in Sparse Field Accesses to False

### ISSUE THREAD

**Issue by mroethlin** [dawn-ico/dusk#61]
If we disregard nested reductions for now, there is only one way to access a sparse field, even in a potentially ambiguous 
situation. Consider:

```
    with levels_upward:        
        outF = sum_over(Edge > Cell > Edge, inF[Edge>Cell>Edge]*sparseF[Edge>Cell>Edge])
```

which is code generated into

```
for (eIdx : mesh.edges())
  linear_idx = 0;
  for (innerEIdx : mesh.nbh(eIdx,ECE))
    outF += inF[innerIdx]*SparseF[eIdx,linear_idx++]
```

Note that this is the only sensible choice to code generate, `SparseF[innerEIdx, linear_idx++]` is unsensical. I would thus propose that sparse fields accesses do not take an index. Also, since the sparse field is accessed with the outer (aka the stage-) index, the offset boolean should default to false.

**Comment by BenWeber42** [comment]
I think this is basically the same as #39 . So you propose that we default to `False` (the only correct possibility) in the non-ambiguous case. In the _still ambiguous_ case (nested reductions), the horizontal index would still be mandatory?

**Comment by mroethlin** [comment]
There is unfortunately a deeper rooted problem here. If there is a nested reduction of depth `n`, each over the same chain with `X->....->X`  (i.e. start = end location), then there are `n+1` possibilities for the dense indices to chose from. This means that the `True|False` representation on the IIR level is not powerful enough. For now, I propose to say blisfuly ignorant on that matter...

**Comment by BenWeber42** [comment]
Yea, I thought we were aware of this limitation and we're deliberately keeping it for now. At least, we have no plans to change that currently?

**Comment by mroethlin** [comment]
Well, I wasn't ;) From what I understand there are no plans to address this at this point in time. From a user perspective, assuming the user wants to translate the ICON dycore, there is no use case for nested reductions. It might, however, be necessary to consider them down the line because of inlining, which would require IIR to be able to represent nested reductions properly.
